name: sdg_main_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - hydra-core=1.3.0
  - pip:
      - hydra-joblib-launcher==1.2.0
      - mlflow==2.0.1
      - python-dotenv==1.0.0
      - wandb==0.13.7
