name: evaluate_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pip:
      - mlflow
      - numpy
      - pandas
      - nltk
      - scikit-learn
      - spacy
      - tensorflow
      - wandb
      - wordcloud
