main:
  project_name: sdg-onu
  experiment_group: development
  steps2execute: # download_data, preprocess_data and split_data are not interesting on the full pipeline
    - train
    - evaluate_model

tracking_server:
  uri:
    aws: http://ec2-18-222-63-55.us-east-2.compute.amazonaws.com:5000
    local: http://0.0.0.0:5000
  default: aws # can be or 'aws' or 'local'

wandb:
  tag:
    titles: cogitus/sdg-onu/titles.json:latest
    authors: cogitus/sdg-onu/authors.json:latest
    affiliations: cogitus/sdg-onu/affiliations.json:latest
    dois: cogitus/sdg-onu/dois.json:latest
    keywords: cogitus/sdg-onu/keywords.json:latest
    abstracts: cogitus/sdg-onu/abstracts.json:latest
    balanced_dataset: cogitus/sdg-onu/balanced_table:latest
    X_train: cogitus/sdg-onu/X_train:latest
    y_train: cogitus/sdg-onu/y_train:latest
    X_valid: cogitus/sdg-onu/X_valid:latest
    y_valid: cogitus/sdg-onu/y_valid:latest
    X_test: cogitus/sdg-onu/X_test:latest
    y_test: cogitus/sdg-onu/y_test:latest

download_data:
  landing_page: https://www.sba.org.br/open_journal_systems/index.php/cba

split_data:
  balancing:
    quantile: 0.5
    random_state: 42
  splitting:
    train_size_factor: 0.9
    test_share_size: 0.2
    random_state: 42
    path_sdg_dataset: /home/alsinaariel/Downloads/SDGs
  advanced_preprocessing:
    tf_batch_size: 32
    tf_seed: 42

train:
  tensorflow_datasets: cogitus/sdg-onu/tensorflow_datasets:latest
  output_sequence_length: 70
  optimizer: RMSprop
  units: 70
  dropout: 0.3
  n_hidden: 1
  epochs: 5
  initial_learning_rate: 0.01
  decay_steps: 6309
  rate: 2
  model_name: RNN_standard

evaluate_model:
  model_tag: cogitus/sdg-onu/RNN_standard:best
  input_data_tag: cogitus/sdg-onu/titles_en.json:latest

defaults:
  - override hydra/job_logging: custom
