main:
  project_name: sdg-onu
  experiment_name: development
  steps2execute:
    - download_data
    - preprocess_data
    - split_data
    - train
    - evaluate_model

data:
  landing_page: "https://www.sba.org.br/open_journal_systems/index.php/cba"
  wandb:
    tag:
      titles: cogitus/sdg-onu/titles.json:latest
      authors: cogitus/sdg-onu/authors.json:latest
      affiliations: cogitus/sdg-onu/affiliations.json:latest
      dois: cogitus/sdg-onu/dois.json:latest
      keywords: cogitus/sdg-onu/keywords.json:latest
      abstracts: cogitus/sdg-onu/abstracts.json:latest
      balanced_dataset: cogitus/sdg-onu/balanced_table:latest
    project: sdg-onu
  balancing:
    quantile: 0.5
    random_state: 42
  splitting:
    train_size_factor: 0.9
    test_share_size: 0.2
    random_state: 42
    path_sdg_dataset: /home/alsinaariel/Downloads/SDGs

defaults:
  - override hydra/job_logging: custom