name: train
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.1.1
  - python=3.10
  - pip:
      - boto3
      - mlflow==2.3.0
      - numpy==1.23.5
      - pandas==2.0.1
      - scikit-learn==1.2.2
      - tensorflow==2.12.0
      - wandb==0.15.0
