name: transform_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.23.0
  - pip=22.1.2
  - python=3.7.13
  - pip:
      - googletrans==3.1.0a0
      - progressbar2==3.38.0
      - wandb==0.12.10