name: preprocess_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.8
  - pip:
      - nltk==3.7
      - numpy==1.21.6
      - pandas==1.3.5
      - requests==2.24.0
      - scikit-learn==1.0.2
      - spacy==3.3.1
      - tensorflow==2.8.2
      - tqdm==4.64.0
      - wandb==0.12.10