name: preprocess_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.1.1
  - python=3.10
  - pip:
      - boto3
      - googletrans==3.1.0a0
      - numpy==1.24.3
      - pandas==2.0.1
      - progressbar2==4.2.0
      - requests==2.30.0
      - wandb==0.15.2
