name: preprocess_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.8
  - pip:
      - googletrans==3.1.0a0
      - numpy
      - pandas
      - requests
      - tqdm
      - wandb