name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.10
  - pip:
      - hydra-core==1.3.0
      - beautifulsoup4==4.6.3
      - progressbar2==4.2.0
      - requests==2.30.0
      - wandb==0.15.2
