name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.7.13
  - pip:
      - beautifulsoup4==4.6.3
      - progressbar2==3.38.0
      - requests=2.23.0
      - wandb==0.12.10