name: split_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - pip:
      - beautifulsoup4==4.6.3
      - hydra-core==1.3.0
      - nltk==3.8.1
      - spacy
      - wandb